name: Build and deploy

on:
  push:
    branches: [ "master" ]

jobs:
  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-latest
    env:
      REPO: ${{ secrets.DOCKER_REPO_UNILAKMET }}
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build and publish
        run: ./mvnw package -Pprod verify jib:build -Djib.to.image=f$REPO:${GITHUB_SHA::8}  -Djib.to.auth.username=${{ secrets.DOCKER_USER }} -Djib.to.auth.password=${{ secrets.DOCKER_PASS }}
